import { Product } from "./types/Product";

export const sampleProduct: Product[] = [
  {
    name: "Name Slim Shirt",
    slug: "name-slim-shirt",
    price: 120,
    image: "/images/p1.jpg",
    countInStock: 10,
    brand: "Nike",
    category: "Shirts",
    rating: 4.5,
    numReviews: 10,
    description: "Sample Description of best nike shirts",
  },
  {
    name: "Adidas Fit Shits",
    slug: "adidas-fit-shirtsd",
    price: 220,
    image: "/images/p2.jpg",
    countInStock: 20,
    brand: "Adidas",
    category: "Shirts",
    rating: 5,
    numReviews: 17,
    description: "Sample Description of best adidas shirts",
  },
  {
    name: "Adidas Fit Pants",
    slug: "adidas-fit-pants",
    price: 220,
    image: "/images/p3.jpg",
    countInStock: 0,
    brand: "Lacoste",
    category: "Pants",
    rating: 4,
    numReviews: 17,
    description: "Sample Description of best adidas pants",
  },
  {
    name: "Name Slim Pants",
    slug: "name-slim-pants",
    price: 120,
    image: "/images/p4.jpg",
    countInStock: 10,
    brand: "Nike",
    category: "Pants",
    rating: 3.5,
    numReviews: 10,
    description: "Sample Description of best nike pants",
  },
];
